### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by JackPai100** [mariostoev/finviz#11]
Hi,

Thank you for sharing this tool, very useful!
I installed finviz with Python 3.7 today, and ran the sample code for screener:

```
from finviz.screener import Screener

filters = ['exch_nasd', 'idx_sp500']  # Shows companies in NASDAQ which are in the S&P500
# Get the first 50 results sorted by price ascending
stock_list = Screener(filters=filters, order='price')
```

I get the following error. Could you please help? Thanks!

```
  File "M:/ Analytics/z/Data/Equity/finviz_scrape.py", line 12, in <module>
    stock_list = Screener(filters=filters, order='price')

  File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\finviz\screener.py", line 65, in __init__
    self.data = self.__search_screener()

  File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\finviz\screener.py", line 222, in __search_screener
    pages_data = async_connector.run_connector()

  File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\site-packages\finviz\helper_functions\request_functions.py", line 61, in run_connector
    loop.run_until_complete(self.__async_scraper())

  File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 560, in run_until_complete
    self.run_forever()

  File "C:\Users\\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 515, in run_forever
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running
```

**Comment by JackPai100** [comment]
I noticed that the error only happens if I run it in spyder. If it is run outside of spyder, everything is fine. Closing the issue.

**Comment by mariostoev** [comment]
Hello @JackPai100,

I'm glad you managed to fix your issue - however, you're not the only one who has alerted me of this problem. I recently received an email about the same error you had. I found out that the issue has to be with the latest release of _tornado_, which is part of the _asyncio_ library. In a similar [thread](https://github.com/jupyter/notebook/issues/3397), people suggested a workaround to this problem by downgrading to _tornado_ 4.5.3. In order to downgrade to the latest working version of _tornado_, run `pip install tornado=4.5.3` in the command prompt.

**Comment by arthurcolle** [comment]
`pip install tornado==4.5.3`

Must be two equal signs

**Comment by jtbales** [comment]
I'll note that it also doesn't work in Python Interactive window in VS Code, but works fine outside of it.

**Comment by draring** [comment]
this solution also does not work with jupyter notebooks, well as far as I've been able to figure out anyway. Jupyter seems to require tornado > 5

**Comment by albertpai** [comment]
On Google Colab, tornado 4.5.3 does not work, but 4.5.2 works well! 
`pip install tornado==4.5.2`
Thank you so much for creating this code!!
