### ISSUE TITLE
Screener missing the first row of every page

### ISSUE THREAD

**Issue by teamKnuepfer** [mariostoev/finviz#128]
columns = [0,1,2,3,4,5,6,7,14,16,24,25,26,30,48,49,50,51,52,53,54,55,56,57,58,63,64,65,66,67,68]
custom = [str(i) for i in columns]
stock_list = Screener(table='Custom', order='Ticker', custom = custom)

Using the above query, the result I get is missing the first row of each page

**Comment by xturtleman** [comment]
I encountered the same issue. See the first column where No starts with 2. 

<img width="997" alt="2022-05-13 19_17_21-Select Anaconda Prompt (Anaconda3) - python" src="https://user-images.githubusercontent.com/39610965/168407227-f6f837d4-d161-4e19-bff5-5c1d46420b3b.png">

**Comment by joeax** [comment]
I thought I was crazy at first, same happening here.

**Comment by diridevelops** [comment]
Yeah this are the problematic lines
https://github.com/mariostoev/finviz/blob/2b1d04cd84931da12c1d5358a210256a9a329ab8/finviz/helper_functions/scraper_functions.py#L22-L27

FinViz has changed the header row to `<tr valign="middle">`, so skipping element 0 now skips a ticker.

**Comment by joeax** [comment]
> FinViz has changed the header row to `<tr valign="middle">`, so skipping element 0 now skips a ticker.

Are you creating a PR to fix? I was suspecting FinViz might be the culprit even though they haven't updated their site in 15 years.
