### ISSUE TITLE
If I do not add a delay to my code, the API will never successfully pull the data.

### ISSUE THREAD

**Issue by vgolf31** [mariostoev/finviz#133]
I use the API to search through every stock I have listed on a text file. However, a week ago, it inexplicably stopped working and only a few stocks could be pulled. Nothing changed in my code either, and the only solution was to add a delay between each request, making the completion time 8x the previous completion time of my program.

**Comment by d3an** [comment]
First, I can't do anything without seeing your code. Secondly, this was an old issue encountered maybe a year ago. Delays are required between some requests to avoid DDOSing the server.

**Comment by frank-besson** [comment]
I was also having this issue. I was using "concurrent.futures.ThreadPoolExecutor" to concurrently process requests. Similar to @vgolf31, I began encountering issues on 7-7-22. Maybe finviz changed their threshold for what qualifies as "DDOSing". 

Scraping using a single thread and a small delay works fine.
