### ISSUE TITLE
Why not use the export link at the bottom of the list?

### ISSUE THREAD

**Issue by RichardBoreiko** [mariostoev/finviz#141]
In the Screener, wouldn't it make sense to just use the export link? You should be able to just load that directly into a dataframe with no need to loop through all the returned rows.

This is the export link with no filters.
https://elite.finviz.com/export.ashx?v=111&ft=2

Or am I missing something?

It looks like the only time the export link doesn't appear on the page is when no rows are returned for the selected filters.

**Comment by d3an** [comment]
Most people don't use FINVIZ*Elite
