### ISSUE TITLE
Bug: Screener output is missing the first row in each page

### ISSUE THREAD

**Issue by pkkishore** [mariostoev/finviz#151]
For example,  please see the DJIA screener results - it is missing the first and 21st rows (for the first and second page)

No.,Ticker,Perf Week,Perf Month,Perf Quart,Perf Half,Perf Year,Perf YTD,Volatility W,Volatility M,Recom,Avg Volume,Rel Volume,Price,Change,Volume
2,WBA,-1.46%,-1.54%,-0.92%,-8.78%,-26.89%,-2.17%,2.47%,2.23%,3.00,6.34M,1.04,36.55,2.07%,"6,604,489"
3,VZ,-3.61%,-2.84%,6.35%,-10.65%,-25.21%,1.55%,1.80%,3.61%,2.80,23.30M,0.66,40.01,0.50%,"15,395,334"
4,CSCO,-2.82%,-3.96%,7.63%,2.96%,-16.04%,-0.80%,1.87%,1.85%,2.50,18.19M,0.96,47.26,1.13%,"17,391,651"
5,KO,-0.35%,-3.85%,1.45%,-5.69%,-2.33%,-6.27%,1.15%,1.54%,2.10,12.87M,1.12,59.62,0.00%,"14,365,076"
6,DOW,-0.30%,3.89%,25.46%,8.25%,-3.50%,18.71%,2.07%,2.32%,2.80,4.99M,0.77,59.82,1.25%,"3,826,254"
7,DIS,-2.39%,12.18%,24.56%,-8.18%,-26.60%,24.38%,3.50%,2.92%,1.90,15.36M,1.01,108.06,-2.08%,"15,508,223"
8,MRK,5.47%,-2.25%,6.87%,22.08%,41.87%,-2.15%,1.82%,2.31%,2.00,9.13M,0.83,108.57,1.73%,"7,607,604"
9,MMM,-3.07%,-11.80%,-8.04%,-23.91%,-30.41%,-5.04%,2.00%,2.67%,3.20,3.15M,0.72,113.88,0.84%,"2,273,345"
10,NKE,-4.22%,-4.46%,32.71%,7.13%,-16.43%,4.46%,2.03%,2.49%,2.20,7.58M,0.69,122.23,0.04%,"5,194,610"
11,IBM,-0.98%,-6.65%,-1.30%,2.31%,-1.59%,-3.75%,1.43%,1.66%,2.50,4.62M,1.03,135.60,1.38%,"4,750,944"
12,PG,-3.05%,-8.23%,1.30%,-4.82%,-13.37%,-8.78%,1.39%,1.60%,2.40,6.77M,1.20,138.26,0.88%,"8,104,155"
13,JPM,-0.04%,1.01%,8.71%,17.40%,-9.94%,5.18%,1.90%,2.10%,2.10,9.92M,0.66,141.04,0.44%,"6,574,502"
14,WMT,1.42%,-1.65%,3.05%,10.71%,4.38%,1.36%,1.28%,1.56%,2.00,6.29M,0.80,143.72,1.55%,"4,999,096"
15,AAPL,-2.26%,13.12%,11.97%,-10.37%,-14.34%,16.22%,2.17%,2.57%,2.00,77.53M,0.74,151.01,0.09%,"57,356,376"
16,JNJ,-1.49%,-7.28%,-5.97%,-2.99%,-5.45%,-8.21%,1.36%,1.71%,2.50,7.13M,0.98,162.15,0.46%,"6,995,567"
17,CRM,-2.34%,15.27%,17.58%,-10.55%,-24.77%,25.97%,2.38%,3.05%,2.10,9.97M,1.13,167.03,-3.82%,"11,246,753"
18,CVX,1.49%,-1.84%,-3.35%,7.74%,24.81%,-4.19%,1.98%,2.12%,2.60,8.36M,1.38,171.97,2.10%,"11,568,125"
19,AXP,0.22%,16.46%,22.89%,9.98%,-8.73%,21.32%,1.74%,2.59%,2.40,3.25M,0.79,179.25,-0.07%,"2,585,315"
20,TRV,2.18%,-2.55%,2.53%,10.63%,8.12%,-0.39%,2.02%,2.40%,2.70,1.37M,0.78,186.75,0.75%,"1,066,423"
22,BA,3.34%,2.34%,26.16%,26.81%,-1.38%,11.76%,2.51%,2.66%,2.00,6.63M,0.73,212.89,0.42%,"4,858,924"
23,V,-1.27%,2.30%,17.16%,7.64%,-1.59%,9.36%,1.35%,1.86%,1.80,6.54M,0.69,227.20,-0.94%,"4,509,510"
24,AMGN,-1.09%,-11.14%,-16.28%,-2.36%,2.24%,-7.67%,1.58%,1.90%,2.70,2.66M,1.01,242.50,1.04%,"2,687,095"
25,CAT,-0.04%,-1.22%,9.81%,27.66%,21.65%,3.39%,2.09%,2.38%,2.60,3.25M,0.86,247.67,0.56%,"2,793,607"
26,MCD,-0.69%,-2.38%,-5.53%,1.21%,0.99%,-0.42%,1.34%,1.66%,2.00,2.87M,1.06,262.42,0.68%,"3,049,610"
27,MSFT,1.84%,11.59%,17.19%,-8.33%,-15.46%,9.71%,2.85%,2.58%,1.80,30.83M,0.83,263.10,-0.20%,"25,734,348"
28,HD,-4.51%,-3.79%,10.39%,1.88%,-13.13%,0.22%,1.75%,2.24%,2.30,3.97M,0.69,316.54,0.31%,"2,732,003"
29,GS,0.36%,1.87%,2.56%,5.57%,-0.87%,8.13%,2.20%,2.65%,2.40,2.66M,0.73,371.28,0.89%,"1,932,912"
30,UNH,4.71%,0.17%,-8.58%,-7.25%,-0.77%,-6.78%,1.73%,2.42%,1.80,3.66M,0.93,494.25,1.75%,"3,417,383"

**Comment by guanch1984** [comment]
second it

**Comment by jdakwa** [comment]
I'm also facing this issue

**Comment by jdakwa** [comment]
@guanch1984 @pkkishore seems like this issue was fixed here https://github.com/mariostoev/finviz/pull/131/files

**Comment by jdakwa** [comment]
Probably just need to upgrade our version
