### ISSUE TITLE
finviz has changed the width of a td

### ISSUE THREAD

**Issue by jacobstac** [mariostoev/finviz#154]
Hi! 
I don't know if its the correct way to write here, but here goes nothing : I got an error using your package version 1.4.5

`  File "/Users/........./venv/lib/python3.10/site-packages/finviz/helper_functions/scraper_functions.py", line 48, in get_total_rows
    etree.tostring(total_element[0]).decode("utf-8").split("</b>")[1].split()[0]
IndexError: list index out of range`

seems like finviz changed the width of the td from 140 to 128 
so changing it [line 44 in scraper_functions.py](https://github.com/mariostoev/finviz/blob/master/finviz/helper_functions/scraper_functions.py#L44) locally solved the issue for me locally.

**Comment by TyrionSnow1911** [comment]
> Hi! I don't know if its the correct way to write here, but here goes nothing : I got an error using your package version 1.4.5
> 
> ` File "/Users/........./venv/lib/python3.10/site-packages/finviz/helper_functions/scraper_functions.py", line 48, in get_total_rows etree.tostring(total_element[0]).decode("utf-8").split("</b>")[1].split()[0] IndexError: list index out of range`
> 
> seems like finviz changed the width of the td from 140 to 128 so changing it [line 44 in scraper_functions.py](https://github.com/mariostoev/finviz/blob/master/finviz/helper_functions/scraper_functions.py#L44) locally solved the issue for me locally.

I can confirm. I updated the td width locally from 140 to 128 and it works now. Can we get this change merged?

**Comment by ferrants** [comment]
https://github.com/mariostoev/finviz/pull/156
