### ISSUE TITLE
It stopped working today after months of good data

### ISSUE THREAD

**Issue by RichardBoreiko** [mariostoev/finviz#155]
Nothing is being returned beginning today, March 28, 2023. It was working yesterday, and I've made no changes to my application. It looks like they've implemented anti-scraping measures.

**Comment by RichardBoreiko** [comment]
Thanks, that worked!

**Comment by atreyasinha** [comment]
Can we get this change merged ASAP!

_helper_functions/scraper_functions.py_
`    total_element = page_content.cssselect('td[width="128"]')`

**Comment by ferrants** [comment]
https://github.com/mariostoev/finviz/pull/156
