### ISSUE TITLE
Header contains line feed code and blank characters when retrieving header

### ISSUE THREAD

**Issue by kaie3** [mariostoev/finviz#174]
An error occurred while executing the script in README.rst

There seems to be a problem retrieving headers.
![1](https://github.com/mariostoev/finviz/assets/44547717/c6a389b1-2af1-4be0-b5f2-cb0a7e93a773)

Please fix it by removing the newline code and empty characters.
```python
    def __get_table_headers(self):
        """ Private function used to return table headers. """
        
        return [header for header in self._page_content.cssselect('tr[valign="middle"]')[0].xpath(
            "td//text()") if header.strip()]
``` 
![2](https://github.com/mariostoev/finviz/assets/44547717/95d0c6e6-aaf1-4d9b-81d2-d6262e749680)

**Comment by RichardBoreiko** [comment]
I'm seeing the same issue:

No.,Ticker,"
    ","
",Company,Sector,Industry,Country,Market Cap,P/E,Price,Change,Volume
1,AMR,"Alpha Metallurgical Resources, Inc.",Basic Materials,Coking Coal,USA,2.52B,2.37,176.65,6.14%,"584,626",,
