### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

### ISSUE THREAD

**Issue by fedseg** [mariostoev/finviz#19]
Attempting to run finviz screener on Python 3.6.5 and tornado 4.5.3.

filters = ['exch_nasd','idx_sp500']
screener = finviz.screener.Screener(filters=filters, order= 'price')

Returns error: RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

Thoughts?

**Comment by ArrrNeo** [comment]
i am trying to run finviz api in django 3.1.1 and i get similar error:

File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.
