### ISSUE TITLE
Error with get_insider()

### ISSUE THREAD

**Issue by mtvu** [mariostoev/finviz#25]
`---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-9-aaef7d24b492> in <module>
----> 1 finviz.get_insider('АAPL')

~/anaconda3/envs/arcticw/lib/python3.7/site-packages/finviz/main_func.py in get_insider(ticker)
     34     """
     35 
---> 36     page_parsed, _ = http_request_get(url=STOCK_URL, payload={'t': ticker}, parse=True)
     37     table = page_parsed.cssselect('table[class="body-table"]')[0]
     38     headers = table[0].xpath('td//text()')

~/anaconda3/envs/arcticw/lib/python3.7/site-packages/finviz/helper_functions/request_functions.py in http_request_get(url, session, payload, parse)
     19         content = requests.get(url, params=payload, verify=False)
     20 
---> 21     content.raise_for_status()  # Raise HTTPError for bad requests (4xx or 5xx)
     22 
     23     if parse:

~/anaconda3/envs/arcticw/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 404 Client Error: Not Found for url: https://finviz.com/quote.ashx?t=%D0%90APL`

**Comment by mariostoev** [comment]
This is the URL you're trying to access: 
https://finviz.com/search.ashx?p=АAPL%60 

As you can see it's truly not found when you click the link. That is because of the %60 is the URL encoding of the ' sign. I guess the parser does not recognise it as a string. Can you try with 'finviz.get_insider("AAPL")' and write a follow-up if it doesn't work. 

Thank you for the contribution!

**Comment by mtvu** [comment]
Hi @mariostoev 

I tried finviz.get_insider('АAPL') and still get the following error

`---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-28-aaef7d24b492> in <module>
----> 1 finviz.get_insider('АAPL')

~/anaconda3/envs/arcticw/lib/python3.7/site-packages/finviz/main_func.py in get_insider(ticker)
     34     """
     35 
---> 36     page_parsed, _ = http_request_get(url=STOCK_URL, payload={'t': ticker}, parse=True)
     37     table = page_parsed.cssselect('table[class="body-table"]')[0]
     38     headers = table[0].xpath('td//text()')

~/anaconda3/envs/arcticw/lib/python3.7/site-packages/finviz/helper_functions/request_functions.py in http_request_get(url, session, payload, parse)
     19         content = requests.get(url, params=payload, verify=False)
     20 
---> 21     content.raise_for_status()  # Raise HTTPError for bad requests (4xx or 5xx)
     22 
     23     if parse:

~/anaconda3/envs/arcticw/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 404 Client Error: Not Found for url: https://finviz.com/quote.ashx?t=%D0%90APL`

**Comment by mariostoev** [comment]
Hey @mtvu,

I tried it on my PC with the latest version of the package, and the command works. The problem should be on your end. I'm sorry.
