### ISSUE TITLE
Industry screening methods? 

### ISSUE THREAD

**Issue by emalcolmb** [mariostoev/finviz#29]
Does this unofficial API contain any methods that allow for screening stocks by industry? If not that would be great.

**Comment by mariostoev** [comment]
Yes it does.

Go to https://finviz.com/screener.ashx and select the industry from the filters above. Notice how the URL changes - if you choose Appliances under industry the URL becomes https://finviz.com/screener.ashx?v=111&f=ind_appliances so in this case the filter for the industry is `ind_appliances`.

> appliances_industry = Screener(filters=['ind_appliances'])

And that's how you use the API to screen for specific industries.

**Comment by emalcolmb** [comment]
Thanks @mariostoev
