### ISSUE TITLE
List of filter strings?

### ISSUE THREAD

**Issue by mmehrle** [mariostoev/finviz#35]
Can someone please post a list of filter strings for the screener? What's the one for the DOW for example? Where do I find them? 

Thanks in advance.

**Comment by mariostoev** [comment]
Hello @mmehrle,

to find the name of the filter you first select it in the finviz website. You will see that the URL query changes and adds the new filter you just chose (it should look something like f='random_filter'). Now you can use the API and refer to the filter inside the code itself. If you have any questions you can email me.

PS: I don't think there's filter for DOW.

**Comment by mmehrle** [comment]
NEVER MIND - I figured it out. It's in the URL when running a screener ;-)

E.g. https://finviz.com/screener.ashx?v=111&f=fa_div_high,ind_exchangetradedfund,sh_avgvol_o50,sh_opt_option

filter = ["fa_div_high", "ind_exchangetradedfund", "sh_avgvol_o50", "sh_opt_option"]

**Comment by tke578** [comment]
@mariostoev great stuff you've done with the api.

FWIR, how about a collection of filter objects for the screener? I'd imagine something like 

```
Screener.filter_options => [ { "exchange":   [ "exch_amex", "exch_nasd", etc.] }
```

I can help if needed.

**Comment by mariostoev** [comment]
@tke578 

In this case you'll need to scrape all filters and their options every time you run the program, which is time consuming. I built the package with the intention for it to be as quick as possible. The only option is to hard code a collection of filter objects inside the project.

Correct me if I'm wrong or didn't understand you.

**Comment by tke578** [comment]
@mariostoev yea that was my thinking about scraping every possible option in the search form which would be time consuming. Another option is to cache/memoize the initial request.

I'd figured it would be nice to have a human readable table format of all the possible search filters rather the tedious spot check/inspect  each filter value.

**Comment by mariostoev** [comment]
@tke578 

The problem with using a cached page is if the finviz website changes. Then it won't be up to date and someone has to always check if the cached page is updated.

Also if you think of a way you are welcome to contribute to the project. Thank you!
