### ISSUE TITLE
Adding custom table settings to the custom table

### ISSUE THREAD

**Issue by whatsthedaydavi** [mariostoev/finviz#37]
Hello,

I'd like to start adding custom table settings like Shares Float, Outstanding Shares, etc. to the custom table in the FinViz module. I've tried doing a few different things like `stock_list.add(Shares_Float = True)`, but so far I haven't found anything that works. Is there a better way to do this?

**Comment by mariostoev** [comment]
Please refer to issue #35. 

If you want to make all the custom settings available as variables you need to hardcode them.
