### ISSUE TITLE
IMPORTANT: 403 Access Forbidden 

### ISSUE THREAD

**Issue by mariostoev** [mariostoev/finviz#45]
The API has been auto-blocked by finviz to stop the requests.

I'm aware of this issue and I'm working on quick-fixing it. When I'm done I'll update the project on GitHub, as well as, PyPi.

**Comment by mariostoev** [comment]
Quick follow-up:

If time is important to you right now and you want the issue fixed right away, I've found a solution. Go to the `request_functions.py` and add a customer header to all request function like this `headers={'User-Agent': 'Mozilla/5.0'}`. I will find a better long-term solution and then I will update the library.

**Comment by mariostoev** [comment]
I've updated `requests_functions.py` with the quick fix on GitHub [here](https://github.com/mariostoev/finviz/commit/8f4a9019f1f1baa3b472ca1030d206d0ce86bd53#diff-7b93e87ebb30407173e97373ad3e6bb9).

**Comment by verdoganai** [comment]
I've solved the issue the same way by cloning the repo. It works for now. Looking forward to seeing a permanent solution though. Thanks!

**Comment by mariostoev** [comment]
The issue is officially resolved and I've uploaded a new version of the package on [pypi](https://pypi.org/project/finviz/1.3.2/). To update to the latest version do `pip install finviz==1.3.2`. 

Finally, guys please make sure you use this library responsibly and not overwhelm the website.

**Comment by parker-moore** [comment]
I'm getting this error when trying to install the latest version. Not sure what I am doing wrong here?

C:\Users\parke>pip install finviz
Collecting finviz
  Using cached finviz-1.3.2.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\parke\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\parke\\AppData\\Local\\Temp\\pip-install-ksygcy7d\\finviz\\setup.py'"'"'; __file__='"'"'C:\\Users\\parke\\AppData\\Local\\Temp\\pip-install-ksygcy7d\\finviz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\parke\AppData\Local\Temp\pip-install-ksygcy7d\finviz\pip-egg-info'
         cwd: C:\Users\parke\AppData\Local\Temp\pip-install-ksygcy7d\finviz\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\parke\appdata\local\programs\python\python38\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\parke\\AppData\\Local\\Temp\\pip-install-ksygcy7d\\finviz\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mariostoev** [comment]
It was a mistake on my part sorry. Now try with `pip install finviz==1.3.4`

**Comment by mmehrle** [comment]
Thanks for fixing this so quickly! Very much appreciated :-)

**Comment by parker-moore** [comment]
Having the same issue with the Portfolio function:

Traceback (most recent call last):
  File "c:\Users\parke\OneDrive\Desktop\StockTrading in Python\v.1.0\finviz porfolio.py", line 37, in <module>
    portfolio = Portfolio('parkermoore4@outlook.com',PASSWORD)
  File "C:\Users\parke\AppData\Local\Programs\Python\Python38\lib\site-packages\finviz\portfolio.py", line 41, in __init__
    auth_response.raise_for_status()
  File "C:\Users\parke\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden: Access is denied. for url: https://finviz.com/login_submit.ashx

**Comment by unreal79** [comment]
Oh my god... How much time I've spent  debugging and (successfully) patching the issue before I realized that I have very outdated version 1.3.4. Works like a charm now.

**Comment by mmehrle** [comment]
> Oh my god... How much time I've spent debugging and (successfully) patching the issue before I realized that I have very outdated Finviz-lib version 1.3.4. Works like a charm now.

Yup that has happened to me before ;-)
