### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by parker-moore** [mariostoev/finviz#46]
requests.exceptions.HTTPError: 403 Client Error: Forbidden: Access is denied. for url: https://finviz.com/screener.ashx?v=Overview&t=&f=sh_price_u50%2Ccap_largeunder%2Cexch_nyse&o=&s=&c=

**Comment by mariostoev** [comment]
This [issue](https://github.com/mariostoev/finviz/issues/45) and already resolved.
