### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by jgrovegeo** [mariostoev/finviz#53]
I've installed via pip and git and receive the same error when trying to use the Screener function

```
from finviz.screener import Screener


filters = ['f=cap_microunder','sh_curvol_o200','sh_float_u100','sh_price_u2','sh_relvol_o3','ta_perf_dup','ta_sma20_pa','ft=4']
stock_list = Screener(filters=filters, table='Performance', order='price')

print(stock_list)
```

`ModuleNotFoundError: No module named 'finviz.screener'; 'finviz' is not a package`

**Comment by nocturnae** [comment]
Not sure if it helps, but you'll get this error if the name of your script overlaps with the module name (e.g. you're using finviz.py) .

**Comment by AdamMuzz** [comment]
I am also experiencing this name error and do not have any file name conflicts
