### ISSUE TITLE
Service does not start pulling filter data in until 10:30AM ish~EST?

### ISSUE THREAD

**Issue by mr-jets** [mariostoev/finviz#55]
While Finviz Elite filter provide pre-market data starting 8AM EST, however the services return 0 results set , until somewhere around 10:30AM EST?

**Comment by mr-jets** [comment]
Suspecting service's server is holding previous day/night's cache without resetting hosting server's stage/status for the right time zone?   Should be an easy fix...

**Comment by d3an** [comment]
Closing because I think this is an issue for the service itself rather than this package.
