### ISSUE TITLE
Doesn't work in colab [RuntimeError: This event loop is already running]

### ISSUE THREAD

**Issue by truecrisis** [mariostoev/finviz#58]
Would be nice if this worked in Google colab:

https://colab.research.google.com/drive/1vLn2Vf2-t0TsHA-rOoJshNjcYUgSmkMh?usp=sharing

![image](https://user-images.githubusercontent.com/19563239/89488961-506c1f80-d7e4-11ea-946b-8ccd9dec785b.png)

**Comment by DuncanF17** [comment]
It did work as recently as about 3 weeks ago but I am having the same issue.

**Comment by truecrisis** [comment]
@mariostoev i don't think this is fixed. (the public collab link i posted above still exhibits the behavior)

but at the same time, i'm GUESSING this happens because finviz is rejecting connections from google collab.
