### ISSUE TITLE
Question about historical screener

### ISSUE THREAD

**Issue by x777** [mariostoev/finviz#66]
Hi, do you have some historical saves of screeners? Thx!

**Comment by d3an** [comment]
Can you clarify what you're asking for? Do you mean a CSV/JSON, URL? Output for any screen? Or do you have one in mind? Also, if you have a use case, we can probably figure out what you mean.

**Comment by x777** [comment]
Imagine that you can see the results of the screener for any day in the past. Maybe you have such a database already?

**Comment by mnalevanko** [comment]
I am pretty sure there is nothing like what you have in mind. Given the tens of filter options Finviz offers, there are millions of different filters the users can create. It doesn't make any sense to store the results of these filters each and every day.

**Comment by x777** [comment]
Y don't understand what you saying. Ok, thanks.

вт, 13 окт. 2020 г., 12:54 Michal Nalevanko <notifications@github.com>:
