### ISSUE TITLE
Screener returns small number of stocks

### ISSUE THREAD

**Issue by mozsoy** [mariostoev/finviz#68]
Since 9/9/2020, there is an issue in Screener that it returns much fewer stocks than usual. In particular, it started return ~100 stocks. Before that date it used to return ~7500 stocks.

Here is the code that I'm running:
stock_list = Screener(table='Performance', order='price')

Here is a screenshot of number of elements(stocks) returned by this code sorted by date:
![image](https://user-images.githubusercontent.com/11222512/94632412-4401c180-027f-11eb-9d64-80f21fa64202.png)

Thanks

**Comment by d3an** [comment]
Code to reproduce problem:
```python
import finviz
scr = finviz.Screener(table='Performance', order='price')
data = scr.get_ticker_details()
print(len(data)) # 100
```

**Comment by tonyz80** [comment]
Hello.
I have also observed that problem. I had sent an email to Mario but best to state it here.

Was the issue from the official FinViz site/server or from changes made to the unofficial API?  
How and when should we anticipate a fix to this issue?
