### ISSUE TITLE
Screener does not return the correct number of stocks

### ISSUE THREAD

**Issue by hayton** [mariostoev/finviz#72]
```
filters2 = ['exch_nasd']

screener = Screener(filters=filters2, table='Performance', order='price')
stocklist = []
for stock in screener:
    stocklist.append(stock['Ticker'])
print(len(stocklist))

```
I run the above code and it returns 280 stocks, while on finviz with this [https://finviz.com/screener.ashx?v=111&f=exch_nasd&ft=4](url) it shows 3205 stocks. 

Am I missing something?

**Comment by hayton** [comment]
Update
when I execute this line `print(len(screener))`, it returns to correct number of stocks.
So how can I get every tickers in the screener object?

**Comment by doubleapple123** [comment]
same issue when using to_csv(), the entries in the csv file does not correlate to the length of the screener or the number of tickers using the filters

**Comment by devbhosale** [comment]
@mariostoev  is the fix released as part of the PIP?
