### ISSUE TITLE
Add getting charts from BigCharts.com

### ISSUE THREAD

**Issue by ghost355** [mariostoev/finviz#75]
Hi, it's not an issue, I just want to add some feature.

I am not a professional coder, but I offer to you adding the function of downloading charts from BigCharts.com 
I just add new def get_bigcharts and a little fix in scraper_functions.py. You can use it to download charts from Screener results

All code is here,
[Gist](https://gist.github.com/ghost355/1bb7cb8dbf09b747509311ed9de2741e)

**Comment by d3an** [comment]
While it may be a good idea to have a scraper for BigCharts.com I don't think this is the right package to address it. The `finviz` package should be used for all-things FinViz and adding features for BigCharts doesn't necessarily fit under that umbrella. This might be subject to change in the future, but right now I don't think it makes sense to add it.
