### ISSUE TITLE
Not getting full results list using the screener

### ISSUE THREAD

**Issue by nerver** [mariostoev/finviz#79]
Hi, I'm trying to use this module to pull all tickers for the NYSE and am running into an issue where I cannot access all the results returned. I have the code below setup to query finviz and get a result set back. It appears to have the right number of results at first, len(stock_list_nyse) returns the same number I see on finviz, but when I try to export to CSV or loop through and print each result I only get between 100 and 160 results (it varies each time). Any ideas what's causing this? Do I need finviz elite in order to see more results?

```
filters = ['exch_nyse']  
stock_list_nyse = Screener(filters=filters, table='Overview', order='Ticker') 

stock_list_nyse.to_csv("stock_list_nyse.csv")

print('Results: ', len(stock_list_nyse))
i = 0
for stock in stock_list_nyse:  # Loop through 10th - 20th stocks
    i = i+1
    print(i, ' - ', stock['Ticker'],' - ', stock['Sector']) 
```

**Comment by d3an** [comment]
Try this one: `pip install -U git+https://github.com/mariostoev/finviz`

**Comment by parker-moore** [comment]
I did this - seems to work but the request takes about a minute or two (much longer than it used to be)

**Comment by d3an** [comment]
@parker-moore FinViz put a rate limiter on requests. Each request returns 20 stocks. Wait times between requests are set to 0.5 seconds, otherwise stocks will be missing in the final results. Depending on how many stocks your screen returns, you can roughly calculate the time it takes to finish.

**Comment by mmehrle** [comment]
yeah I'm having the same issue and I just installed finviz.

**Comment by mmehrle** [comment]
If you run this code please look at the CSV it produces:

rom finviz.screener import Screener
import nest_asyncio
nest_asyncio.apply()

#filter = ["idx_sp500"]
filter = ["geo_usa", "sh_avgvol_o2000", "sh_opt_optionshort", "sh_price_o30"]
stock_list = Screener(filters=filter, order='volume')
print ("%s symbols listed.\n" % len(stock_list))
stock_list.to_csv("finviz_list.csv")

I look at the CSV and it starts at some random line and only prints 100 lines or so. 

How does that make any sense??

**Comment by bardvir** [comment]
worked for me as well, although after the new pip install, when trying to call the scanner i encountered the following error:
`"TypeError: __init__() missing 1 required keyword-only argument: 'css_select'"`

it's probably related to my python version (3.8.5), 
I had to explicitly add parameter **css_select=False** in line 335 of screener.py, and then it worked as expected.

Changed this:
`async_connector = Connector(scrape.download_chart_image, chart_urls, css_select=False)`
To this:
`async_connector = Connector(scrape.download_chart_image, chart_urls)`
