### ISSUE TITLE
AttributeError when importing Screener from an external directory

### ISSUE THREAD

**Issue by kieran-mackle** [mariostoev/finviz#90]
Hi,

I am encountering an attribute error when trying to import the screener module from any directory which is not the finviz-master directory.

Everything works as expected when running, for example, the example.py file included in the parent directory, but even if I copy this file out into a different directory and try run it from there, I get the following error:

> AttributeError: type object  'Screener' has no attribute 'load_filter_dict'

Is there a way around this when importing finviz.screener?

Thanks in advance

**Comment by d3an** [comment]
`example.py` seems to work. Closing this now.
