### ISSUE TITLE
not getting all stocks from API 

### ISSUE THREAD

**Issue by JamesTrewern** [mariostoev/finviz#93]
len(stock_list) gives me 920 which is the amount of stocks i get on the finviz website. But i can't address higher than stock_list[100]

The 'no.' column also has weird gaps so the 101 stocks i'm getting back are not just the first 100 stocks

![a1](https://user-images.githubusercontent.com/75040548/113375915-6678b280-9368-11eb-8a1a-ba0b7bb66dc2.PNG)
![a2](https://user-images.githubusercontent.com/75040548/113375917-67114900-9368-11eb-9927-bc42530f031f.PNG)
![a3](https://user-images.githubusercontent.com/75040548/113375919-67114900-9368-11eb-8a48-857c1ec6e695.PNG)

**Comment by d3an** [comment]
```bash
$ pip install -U git+https://github.com/mariostoev/finviz
```

**Comment by Jorgeruiz97** [comment]
#### I am currently having the same issue. My screener returns 3k rows, but when I try to access the data as a List of dicts it only returns 100 🤔

**Comment by Jorgeruiz97** [comment]
> ```shell
> $ pip install -U git+https://github.com/mariostoev/finviz
> ```

This fixes the issue, now I am getting all the rows, thank you
